# Generated by Django 5.0.6 on 2024-07-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee')], max_length=50),
        ),
    ]
