# Generated by Django 5.0.6 on 2024-07-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='project_id',
        ),
    ]
