# Generated by Django 5.0.6 on 2024-07-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_rename_project_task_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='project',
        ),
    ]
